---
title: "ELISA-analysis"
author: "Lakshmi Batachari"
date: "September 20, 2018"
output: html_document
---

```{r, message = FALSE}

library(readxl)
library(tidyverse)
library(dplyr)
library(cluster)
source("ELISA functions.R")

theme_set(theme_classic())

```

```{r}
fileName <- c("ELISA_data/092518 IFNg ELISA Plate2.xlsx")
standards <- read_excel(fileName, sheet = 2)
OD450data <- read_excel(fileName, sheet = 3)
```

```{r}
meanStandards <- standards %>%
                    group_by(agConc)%>%
                    summarize(meanStandard = mean(OD450))
 
ggplot(meanStandards) + 
  geom_point(aes(x=`meanStandard`, y=`agConc`))

linearFit <- lm(agConc~meanStandard, data = meanStandards)

y_intercept <- linearFit$coefficients[1]
slope <- linearFit$coefficients[2]


```
Calculate and plot cytokine concentrations
```{r}
cytokineName <- "IL17"

cytokineConc <- OD450data %>%
  group_by(sampleName, ID, dilutionFactor, cytokine) %>%
  summarize(meanValue = mean(OD450)) %>%
  mutate(`concentration` = max(0, (meanValue*slope + y_intercept)*dilutionFactor))

ggplot(cytokineConc, aes(x = ID, y = concentration)) + 
  geom_bar(stat = "identity")+
  xlab("Sample Name") +
  ylab("Concentration (pg/mL)") + 
  ggtitle(cytokineName) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), plot.title = element_text(hjust = 0.5))



```





