---
title: "ELISA-multi analysis"
author: "Lakshmi Batachari"
date: "September 20, 2018"
output: html_document
---

```{r, message = FALSE}
library(readxl)
library(tidyverse)
theme_set(theme_classic())
source("ELISA functions.R")
library("dendextend")
library(ape)
library(ggdendro)
library(factoextra)
library(cluster)
library(NbClust)
```

Calculate concentrations for each file and combine data frame
```{r}
fileNames <- c("ELISA_data/091918 IL10 ELISA Plate1.xlsx","ELISA_data/091918 IL10 ELISA Plate2.xlsx", "ELISA_data/092518 IFNg ELISA Plate1.xlsx", "ELISA_data/092518 IFNg ELISA Plate2.xlsx", "ELISA_data/092518 IL17 ELISA Plate1.xlsx", "ELISA_data/092518 IL17 ELISA Plate2.xlsx")

processedFiles <- map(fileNames, analyze)
combinedData <- bind_rows(processedFiles)
```

Create a plot for each cytokine

```{r}
#IL10 
IL10only <- combinedData %>%
  filter(cytokine=="IL10")

ggplot(IL10only)+
  geom_bar(stat = "identity", aes(x = reorder(sampleName, -concentration), y = concentration)) +
  ggtitle("IL10") +
  xlab("Bacterial Product")+
  ylab("Concentration (pg/ml)")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6), plot.title = element_text(hjust = .5))

#IFNg
IFNgonly <- combinedData %>%
  filter(cytokine=="IFNg")

ggplot(IFNgonly)+
  geom_bar(stat = "identity", aes(x = reorder(sampleName, -concentration), y = concentration)) +
  ggtitle("IFNg")+
  xlab("Bacterial Product")+
  ylab("Concentration (pg/ml)")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6), plot.title=element_text(hjust = .5))

#IL17
IL17only <- combinedData %>%
  filter(cytokine=="IL17")

ggplot(IL17only)+
  geom_bar(stat = "identity", aes(x = reorder(sampleName, -concentration), y = concentration)) +
  ggtitle("IL17")+
  xlab("Bacterial Product")+
  ylab("Concentration (pg/ml)")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6), plot.title=element_text(hjust = .5))

```



Plot all samples
```{r}

#plot by sample name, differentiate cytokines with different colors
ggplot(combinedData) + 
  geom_bar(stat = "identity", aes(x = sampleName, y = concentration, fill = cytokine), position = "dodge") +
  xlab("Sample Name") +
  ylab("Concentration (pg/mL)") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size =6))

#plot by sample ID
ggplot(combinedData, aes(x = ID, y = concentration)) + 
  geom_bar(stat = "identity") +
  xlab("Sample ID") +
  ylab("IL-10 Concentration (pg/mL)") + 
  scale_x_continuous(breaks = seq(1, 60, 1))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size =7))

#facet by cytokine
ggplot(combinedData) + 
  geom_bar(stat = "identity", aes(x = reorder(sampleName, -concentration), y = concentration, fill = factor(cytokine)))+
  facet_grid(cytokine~., scales = "free") +
  xlab("Sample Name") +
  ylab("Concentration (pg/mL)") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size =6), legend.position = "none") 

  
#reorder(sampleName, -concentration)
```

K-means cluster
```{r}
IL10values <- subset(combinedData, cytokine == "IL10", 
select=c(sampleName, concentration))
names(IL10values)[2]<-"IL10"

IFNgvalues <- subset(combinedData, cytokine == "IFNg", 
select=c(sampleName, concentration))
names(IFNgvalues)[2]<-"IFNg"

IL17values <- subset(combinedData, cytokine == "IL17", 
select=c(sampleName, concentration))
names(IL17values)[2]<-"IL17"

a <- merge(IL10values, IFNgvalues)
mergedData <- merge(a, IL17values)

#remove NAs and scale data so that mean = 0 and SD = 1
mergedData <- na.omit(mergedData)
mergedData.scaled <- scale(mergedData[, -1])

#set seed ensures that results are reproducible by defining the number of initial centroids
set.seed(4)

#Perform k-means cluster analysis, nstart sets the number of initial configurations before choosing optimal one
k5 <- kmeans(mergedData.scaled, centers = 5, nstart = 25)

#Re-introduce sample names to each row
row.names(mergedData.scaled) <- mergedData[,1]

#Create a plot to show clusters
fviz_cluster(k5, data = mergedData.scaled,
             palette = "Set2", 
             star.plot = FALSE, # Add segments from centroids to items
             repel = TRUE, # Avoid label overplotting (slow)
             ggtheme = theme_classic(), 
             labelsize = 6, 
             main = "K-means Cluster Analysis",
             xlab = FALSE,
             ylab = FALSE
             )

#determine optimal number of clusters using Elbow method
fviz_nbclust(mergedData.scaled, kmeans, method = "wss") +
  geom_vline(xintercept = 4, linetype = 2) +
  labs(subtitile = "Elbow method")

#add new column containing cluster group to mergedData
mergedData.clusters <- cbind(mergedData, group = k5$cluster)

high <- filter(mergedData.clusters, group == "3") 

low <- filter(mergedData.clusters, group == "4") 
 




```
```{r}
DF <- IFNgonly$concentration
  DF <- na.omit(DF)
  DF <- scale(DF)
  row.names(DF) <- IFNgonly$sampleName
  
  
  dist <- dist(DF)
  hc1 <- agnes(DF, method = "ward")
  dend <- as.dendrogram(hc1)
  
  
  pdf("dendro.pdf", width = 15, height = 15)
  samplePlot <- fviz_dend(dend, k = 3, cex = 1, color_labels_by_k = TRUE,type = "circular")
  
  print(samplePlot)
  dev.off()
```


Hierarchical clustering ward method
```{r}

#perform ward method hierarchical cluster analysis
wardHCA(IFNgonly)



```
```{r}
df <- IL10only

#define different clustering methods
m <- c("average", "single", "complete", "ward")
names(m)<- c("average", "single", "complete", "ward")

#compute agglomerative coefficient, which measures the quality of agg clustering
ac <- function(x) {
  agnes(df, method = x)$ac
}

map_dbl(m, ac)





#get_leaves_nodePar(dend)[[1]]
#par( mfrow = c(1,1), mar= c(2, 6, 0.000001, 10))

#plot(dend, horiz = TRUE, center = TRUE,  xlab = "Height")

#plot(hc1, cex = 0.5)

#groups <- cutree(hc1, k =5)
#rect.hclust(hc1, k=4, border = "brown1")
```

```{r}

plot(IL10only$concentration)

par (mfrow = c(2,2)) 
for (i in 1:4) {
  set.seed(4)
  clusters <-kmeans(mergedData.scaled, centers= 4) 
  plot(IL10only$concentration, col = clusters$cluster)
  }

```

```{r}
highlowDF<- read_excel("ELISA_data/High low subset.xlsx")

ggplot(highlowDF, aes(y = bacteria, x = cytokine)) + 
  geom_tile(aes(fill = level)) + 
  scale_fill_manual(values = c("#20b2aa", "#ff6961"), name = "Level")+
  labs( x = "Cytokine", y = "Bacterial Product", title = "Relative Cytokine Levels") + 
  theme_classic() 
  
  


```
